<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions\" />
    <Folder Include="Facade\" />
    <Folder Include="Model\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DrWavDotNet" Version="0.13.7.20230108" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fletch.Audio\Fletch.Audio.csproj" />
    <ProjectReference Include="..\Fletch.Core\Fletch.Core.csproj" />
  </ItemGroup>

</Project>
