<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Facade\**" />
    <EmbeddedResource Remove="Facade\**" />
    <None Remove="Facade\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fletch.Engine\Fletch.Engine.csproj" />
  </ItemGroup>

</Project>
