<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Content\**" />
    <EmbeddedResource Remove="Content\**" />
    <None Remove="Content\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fletch.Assets\Fletch.Assets.csproj" />
    <ProjectReference Include="..\Fletch.Audio.Silk.NET.OpenAL\Fletch.Audio.Silk.NET.OpenAL.csproj" />
    <ProjectReference Include="..\Fletch.Audio\Fletch.Audio.csproj" />
    <ProjectReference Include="..\Fletch.Core\Fletch.Core.csproj" />
    <ProjectReference Include="..\Fletch.Input.MonoGame\Fletch.Input.MonoGame.csproj" />
    <ProjectReference Include="..\Fletch.Input\Fletch.Input.csproj" />
    <ProjectReference Include="..\Fletch.Physics\Fletch.Physics.csproj" />
    <ProjectReference Include="..\Fletch.Platform\Fletch.Platform.csproj" />
    <ProjectReference Include="..\Fletch.Rendering.MonoGame\Fletch.Rendering.MonoGame.csproj" />
    <ProjectReference Include="..\Fletch.Rendering\Fletch.Rendering.csproj" />
    <ProjectReference Include="..\Fletch.Runtime\Fletch.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="ppy.SDL2-CS" Version="1.0.82" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

</Project>
